In [1]:
import os
from vp_analysis_api import VPAnalysisAPI

# generate and download api key file from https://portal.variantperception.com/vp-data-api
# save the value in your local user directory (C:/Users/John/vp_api_key.txt)
# or set the key as an environment variable: VP_ANALYSIS_API_KEY 
if "VP_ANALYSIS_API_KEY" in os.environ:
    print("Reading API key from environment")
    api_key = os.environ.get("VP_ANALYSIS_API_KEY")
else:
    with open(os.path.expanduser('~/vp_api_key.txt'), 'r') as file:
        print("Reading API key from file")
        api_key = file.read().replace('\n', '')
print(f"API Key: {api_key[:5]}...")
api = VPAnalysisAPI(api_key)

Reading API key from environment
API Key: eyJhb...

In [2]:
# There are two data types: 
# 1. macro time series 
# 2. time series for a particular asset and factor

# First, we show how macro data works
# This will return a list of all macro data identifiers
macro_series = api.get_macro_series_list()
macro_series

,ticker,name,model,asset,region
0,bcfi24,VP BCFI,liquidity,macro,world
1,cb_policy_au_hiking,AU Central Bank Hiking Regime,cb_policy,macro,au
2,cb_policy_br_hiking,BR Central Bank Hiking Regime,cb_policy,macro,br
3,cb_policy_ca_hiking,CA Central Bank Hiking Regime,cb_policy,macro,ca
4,cb_policy_ch_hiking,CH Central Bank Hiking Regime,cb_policy,macro,ch
...,...,...,...,...,...
3039,vp_macro_regime_prob,VP Macro Risk Indicator,macro_regimes,macro,world
3040,vp_macro_risk_gr_prob,VP Macro Risk Indicator - Growth Dimension,macro_regimes,macro,world
3041,vp_macro_risk_infl_prob,VP Macro Risk Indicator - Inflation Dimension,macro_regimes,macro,world
3042,vp_macro_risk_liq_prob,VP Macro Risk Indicator - Liquidity Dimension,macro_regimes,macro,world
3043,vp_macro_risk_pol_prob,VP Macro Risk Indicator - Policy Dimension,macro_regimes,macro,world

In [3]:
# Search the list for the desired ticker (or use the interactive UI on the portal)
lei_us_grow_id = macro_series.query("name == 'United States Real GDP Leading Indicator'").ticker.squeeze()
print(lei_us_grow_id)

ex_liq_id = macro_series.query("name == 'Global Excess Liquidity'").ticker.squeeze()
print(ex_liq_id)

# Fetch the data
# The column headers will show VP's data id format, which is vp:ticker, with [0] at the end for first revision data
df = api.get_df_from_macro_series_list([lei_us_grow_id, ex_liq_id], start_date='2010-01-01', end_date='2011-01-01', first_revision=True)
df

lei_us_grow_rgdp
globexliq24

            vp:lei_us_grow_rgdp[0]  vp:globexliq24[0]
dt
2010-01-31                2.060704          10.728616
2010-02-28                2.390395           9.098519
2010-03-31                2.336014          10.799719
2010-04-30                2.740704           5.755906
2010-05-31                3.526895           2.575121
2010-06-30                2.998410          -5.845586
2010-07-31                2.055410          -4.001016
2010-08-31                1.808110          -1.544045
2010-09-30                1.665542          -2.004566
2010-10-31                1.790518           0.155336
2010-11-30                1.877816           1.019836
2010-12-31                2.037027          -2.327133

In [4]:
# To get last revision data:
df = api.get_df_from_macro_series_list([lei_us_grow_id, ex_liq_id], start_date='2010-01-01', end_date='2011-01-01', first_revision=False)
df

            vp:lei_us_grow_rgdp  vp:globexliq24
dt
2010-01-31             3.876191       10.998414
2010-02-28             3.976509        9.535392
2010-03-31             3.846621       11.277938
2010-04-30             3.737906        6.143061
2010-05-31             4.207935        2.976225
2010-06-30             3.901775       -5.386598
2010-07-31             3.285562       -3.796025
2010-08-31             3.170152       -1.348720
2010-09-30             3.276804       -1.746002
2010-10-31             3.393756        0.222463
2010-11-30             3.324914        0.983319
2010-12-31             3.236292       -2.107850

In [5]:
# Next, there is asset-factor data

# This will return all the public factors:
factors = api.get_factors()
factors

,index,factor_identifier,is_macro,factor_name,factor_description
0,20,capital_cycle_score,1.0,VP Capital Cycle Score,Composite score ranking firms by net investmen...
1,27,ccl_invs,1.0,Capital Cycle Input: Net Investment,Capital Cycle Score input measuring net invest...
2,28,ccl_rmw,1.0,Capital Cycle Input: Net ROIC,Capital Cycle Score input measuring net return...
3,29,ccl_rxs,1.0,Capital Cycle Input: ROIC Ranking,Capital Cycle Score input ranking ROIC across ...
4,62,fval,1.0,VP Fair Value Upside,Percentage upside or downside relative to the ...
5,66,fxe_sc,1.0,VP FX Edge (Scaled),Scaled VP FX Edge currency timing signal
6,91,lp_brd,1.0,LPPL Breadth,Percentage of index constituents with active L...
7,92,lp_dbf,1.0,LPPL Daily Bubble Pattern,LPPL bubble (sell) pattern detected on daily p...
8,93,lp_dcf,1.0,LPPL Daily Crash Pattern,LPPL crash (buy) pattern detected on daily prices
9,108,lppl3,1.0,LPPL Composite Signal,LPPL composite pattern signal: positive for bu...
10,109,lppl_bubble,1.0,LPPL Bubble Pattern Strength,Share of LPPL fits currently flagging an activ...
11,110,lppl_crash,1.0,LPPL Crash Pattern Strength,Share of LPPL fits currently flagging an activ...
12,111,lppl_fnd,1.0,LPPL Pattern Found,"LPPL pattern detected: +1 for buys, -1 for sel..."
13,112,lppl_sig,1.0,LPPL Signal Trigger,"LPPL trade signal triggered: +1 for buys, -1 f..."
14,158,quality_score,1.0,VP Quality Score,Composite quality score combining profitabilit...
15,179,tol_rt,1.0,Tactical Outlook 1M Return Forecast,Predicted 1-month total return from the VP Tac...
16,211,vp_crowding_score,1.0,VP Crowding Score,Composite stock-popularity score combining fas...
17,213,vp_fast_money,1.0,VP Fast Money,Speculative activity gauge measuring trades th...
18,216,vwap_1y,1.0,1 Year VWAP (Local),Volume-weighted average price over the past ye...
19,217,vwap_3y,1.0,3 Year VWAP (Local),Volume-weighted average price over the past th...
20,218,firr,NaN,VP Forecast IRR,Estimate of single stock expected long-run ann...

In [6]:
# This returns all the macro assets:
macro = api.get_macro_assets()
macro

    asset_id                                      name     assetclass country
0        spx                  S&P 500 Index (ETF: SPY)  equity region      us
1        qqq                      Nasdaq 100 ETF (QQQ)  equity region      us
2        iwm                    Russell 2000 ETF (IWM)  equity region      us
3       xmmo    Invesco S&P MidCap Momentum ETF (XMMO)  equity region      us
4       qgrw  WisdomTree US Quality Growth Fund (QGRW)  equity region      us
..       ...                                       ...            ...     ...
334  gb5yswp                            GBP IRS 5 Year   fixed income      gb
335   ushysp                     USD High Yield Spread   fixed income      us
336   usigsp               USD Investment Grade Spread   fixed income      us
337   eu3bsp                    Euro BBB Credit Spread   fixed income      eu
338      vix                                       VIX  equity region      us

[339 rows x 4 columns]

In [7]:
# This returns the single stock equity assets:
equities = api.get_equity_assets()
equities

,asset_id,name,country,industry
0,000001:SZSE,"Ping An Bank Co., Ltd.",China,Banks
1,000002:SZSE,"China Vanke Co., Ltd.",China,Real Estate Management and Development
2,000006:SZSE,"Shenzhen Zhenye (Group) Co.,Ltd.",China,Real Estate Management and Development
3,000009:SZSE,"China Baoan Group Co., Ltd.",China,Industrial Conglomerates
4,000012:SZSE,"CSG Holding Co., Ltd.",China,Construction Materials
...,...,...,...,...
12555,ZVOI:OTCPK,Zovio Inc,United States,Diversified Consumer Services
12556,ZVRA:NasdaqGS,"Zevra Therapeutics, Inc.",United States,Pharmaceuticals
12557,ZWS:NYSE,Zurn Elkay Water Solutions Corporation,United States,Building Products
12558,ZYDUSLIFE:NSEI,Zydus Lifesciences Limited,India,Pharmaceuticals
12559,ZYME:NasdaqGS,Zymeworks Inc.,United States,Biotechnology

In [8]:
# To get asset-factor data, find the asset id and factor id of the data you are looking for
# You can do this by searching through the dataframes above, or by using the interactive UI on the portal
fast_money_id = factors.query("factor_name == 'VP Fast Money'").factor_identifier.squeeze()
print(fast_money_id)
cap_cycle_id = factors.query("factor_name == 'VP Capital Cycle Score'").factor_identifier.squeeze()
print(cap_cycle_id)

spx_id = macro.query("name == 'S&P 500 Index (ETF: SPY)'").asset_id.squeeze()
print(spx_id)
apple_id = equities.query("name == 'Apple Inc.'").asset_id.squeeze()
print(apple_id)

# Finally, fetch the data
df = api.get_df_from_asset_factor_list([(spx_id, fast_money_id), (apple_id, cap_cycle_id)], start_date='2010-01-01', end_date='2010-01-15', first_revision=True)

# The column headers will contain VP's data id format, which is vp:ss:asset$factor (and [0] for first revision)
df

vp_fast_money
capital_cycle_score
spx
AAPL:NasdaqGS

,vp:ss:spx$vp_fast_money[0],vp:ss:AAPL:NasdaqGS$capital_cycle_score[0]
dt,,
2010-01-01,57.164359,76.749874
2010-01-02,NaN,86.099097
2010-01-03,NaN,86.074832
2010-01-04,58.463381,72.813975
2010-01-05,58.446056,72.832861
2010-01-06,58.352957,72.851747
2010-01-07,58.533319,72.870633
2010-01-08,58.759974,72.889518
2010-01-09,NaN,85.957438
2010-01-10,NaN,85.932545
2010-01-11,58.980043,72.946176
2010-01-12,58.242386,72.965061
2010-01-13,58.980485,72.983947
2010-01-14,59.203439,73.002833
2010-01-15,57.858703,73.021719